server:
  port: 8001
mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    hikari:
      username: root
      password: aabbcc570
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool

#热部署配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java/vip/zhguo

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#    static-path-pattern: static/**  #配置后无法访问swagger,不配置头像无法放行，后续优化





