server:
  port: 8002
aliyun:
  oss:
    AccessKeyID:
    AccessKeySecret:
    bucKetName: zhguo-oss
    endpoint: oss-cn-shanghai.aliyuncs.com
    folderName: avatar/
spring:
  application:
    name: service-oss
  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER